(function(g){var window=this;var PDa=function(a,b){return g.Wb(a,b)},l6=function(a){g.bn(a,"zx",g.vb());
return a},m6=function(a,b,c){g.xa(c)||(c=[String(c)]);
g.en(a.o,b,c)},QDa=function(a,b){var c=[];
g.Pk(b,function(a){try{var b=g.DD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.CD(b)&&c.push(a):c.push(a)},a);
return c},RDa=function(a,b){var c=QDa(a,b);
(0,g.D)(c,function(a){g.DD.prototype.remove.call(this,a)},a)},SDa=function(a){if(a.Nd){if(a.Nd.locationOverrideToken)return{locationOverrideToken:a.Nd.locationOverrideToken};
if(null!=a.Nd.latitudeE7&&null!=a.Nd.longitudeE7)return{latitudeE7:a.Nd.latitudeE7,longitudeE7:a.Nd.longitudeE7}}return null},TDa=function(a,b,c,d){var e=new g.Tm(null,void 0);
a&&g.Um(e,a);b&&g.Vm(e,b);c&&g.Wm(e,c);d&&g.Xm(e,d);return e},UDa=function(a){g.hG[a]&&(a=g.hG[a],(0,g.D)(a,function(a){g.fG[a]&&delete g.fG[a]}),a.length=0)},VDa=function(a){var b=g.eG();
if(b)if(b.clear(a),a)UDa(a);else for(var c in g.hG)UDa(c)},n6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Nm;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",WDa(this,a.capabilities||""),XDa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},WDa=function(a,b){a.capabilities.clear();
(0,g.Wd)(b.split(","),g.Da(PDa,YDa)).forEach(function(b){a.capabilities.add(b)})},XDa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},o6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},p6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},ZDa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},$Da=function(a){return new o6(a)},aEa=function(a){return g.xa(a)?(0,g.I)(a,$Da):[]},q6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},r6=function(a){return g.xa(a)?"["+(0,g.I)(a,q6).join(",")+"]":"null"},s6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},bEa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},t6=function(a,b){return g.Ja(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},u6=function(a,b){return g.Ja(a,function(a){return p6(a,b)})},cEa=function(){var a=(0,g.sH)();
a&&RDa(a,a.o.fe(!0))},v6=function(){var a=g.vH("yt-remote-connected-devices")||[];
g.fb(a);return a},dEa=function(a){if(g.Oa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},eEa=function(a){g.uH("yt-remote-connected-devices",a,86400)},x6=function(){if(w6)return w6;
var a=g.vH("yt-remote-device-id");a||(a=s6(),g.uH("yt-remote-device-id",a,31536E3));for(var b=v6(),c=1,d=a;g.Na(b,d);)c++,d=a+"#"+c;return w6=d},y6=function(){var a=v6(),b=x6();
g.Na(a,b);g.xH()&&g.ib(a,b);a=dEa(a);if(g.Oa(a))try{g.QG("remote_sid")}catch(c){}else try{g.PG("remote_sid",a.join(","),-1)}catch(c){}},fEa=function(){return g.vH("yt-remote-session-browser-channel")},gEa=function(){return g.vH("yt-remote-local-screens")||[]},hEa=function(){g.uH("yt-remote-lounge-token-expiration",!0,86400)},iEa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(gEa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.Bm)(c,function(a){return!g.Na(b,a)})&&hEa();
g.uH("yt-remote-local-screens",a,31536E3)},jEa=function(a,b){g.uH("yt-remote-session-browser-channel",a);
g.uH("yt-remote-session-screen-id",b);var c=v6(),d=x6();g.Na(c,d)||c.push(d);eEa(c);y6()},z6=function(a){a||(g.wH("yt-remote-session-screen-id"),g.wH("yt-remote-session-video-id"));
y6();a=v6();g.Ta(a,x6());eEa(a)},kEa=function(){if(!A6){var a=g.OD();
a&&(A6=new g.xD(a))}return A6?!!A6.get("yt-remote-use-staging-server"):!1},lEa=function(){var a=window.document.createElement("a");
g.id(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ab(a)},mEa=function(a,b,c){c=void 0===c?null:c;
var d=g.Pd("SCRIPT");d.id=a;d.onload=function(){b&&(0,window.setTimeout)(b,0)};
d.onreadystatechange=function(){switch(d.readyState){case "loaded":case "complete":d.onload()}};
c&&d.setAttribute("nonce",c);g.kd(d,g.ne("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));a=window.document.getElementsByTagName("head")[0]||window.document.body;a.insertBefore(d,a.firstChild);return d},nEa=function(a){a=void 0===a?null:a;
var b=lEa(),c=window.document.getElementById(b),d=c&&g.qF(c,"loaded");d||c&&!d||(c=mEa(b,function(){g.qF(c,"loaded")||(g.pF(c,"loaded","true"),g.lG(b),g.pE(g.Da(VDa,b),0))},a))},oEa=function(){var a=void 0===a?null:a;
window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):nEa(a)},B6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},pEa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},C6=function(a){a.length?qEa(a.shift(),function(){C6(a)}):D6()},rEa=function(a){return"chrome-extension://"+a+E6},qEa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},F6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},D6=function(){var a=pEa();
a&&a(!1,"No cast extension found")},G6=function(){if(sEa){var a=2,b=pEa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;qEa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",D6,c)}},tEa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(G6(),a({command:"cast.sender.init"}))},uEa=function(){G6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);C6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+E6,"//www.gstatic.com/eureka/clank"+E6])},H6=function(a,b,c){g.L.call(this);
this.F=null!=c?(0,g.B)(a,c):a;this.Fd=b;this.D=(0,g.B)(this.vL,this);this.o=!1;this.A=0;this.B=this.Fa=null;this.C=[]},I6=function(){},J6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Z=new g.jn(this);this.A=new g.Cg;this.A.setInterval(250)},wEa=function(a,b,c){a.xk=1;
a.Ph=l6(b.clone());a.Dj=c;a.D=!0;vEa(a,null)},K6=function(a,b,c,d,e){a.xk=1;
a.Ph=l6(b.clone());a.Dj=null;a.D=c;e&&(a.JF=!1);vEa(a,d)},vEa=function(a,b){a.wl=(0,g.H)();
L6(a);a.si=a.Ph.clone();m6(a.si,"t",a.F);a.eo=0;a.Xc=a.o.qt(a.o.Wn()?b:null);0<a.Zt&&(a.dr=new g.ul((0,g.B)(a.eH,a,a.Xc),a.Zt));a.Z.X(a.Xc,"readystatechange",a.PW);var c=a.dj?g.dc(a.dj):{};a.Dj?(a.Ur="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Xc.send(a.si,a.Ur,a.Dj,c)):(a.Ur="GET",a.JF&&!g.Kd&&(c.Connection="close"),a.Xc.send(a.si,a.Ur,null,c));a.o.Hf(1)},zEa=function(a,b,c){for(var d=!0;!a.Oi&&a.eo<c.length;){var e=xEa(a,c);
if(e==M6){4==b&&(a.Qh=4,N6(15),d=!1);break}else if(e==yEa){a.Qh=4;N6(16);d=!1;break}else O6(a,e)}4==b&&0==c.length&&(a.Qh=1,N6(17),d=!1);a.Of=a.Of&&d;d||(P6(a),Q6(a))},xEa=function(a,b){var c=a.eo,d=b.indexOf("\n",c);
if(-1==d)return M6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return yEa;d+=1;if(d+c>b.length)return M6;var e=b.substr(d,c);a.eo=d+c;return e},BEa=function(a,b){a.wl=(0,g.H)();
L6(a);var c=b?window.location.hostname:"";a.si=a.Ph.clone();g.bn(a.si,"DOMAIN",c);g.bn(a.si,"t",a.F);try{a.Pf=new window.ActiveXObject("htmlfile")}catch(n){P6(a);a.Qh=7;N6(22);Q6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in R6)k=R6[l];else if(l in AEa)k=R6[l]=AEa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=R6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.ld(g.Bc("b/12014412"),d+"</body></html>");a.Pf.open();a.Pf.write(g.bd(c));a.Pf.close();a.Pf.parentWindow.m=(0,g.B)(a.XV,a);a.Pf.parentWindow.d=(0,g.B)(a.SE,a,!0);a.Pf.parentWindow.rpcClose=(0,g.B)(a.SE,a,!1);c=a.Pf.createElement("DIV");a.Pf.parentWindow.document.body.appendChild(c);d=g.Pc(a.si.toString());d=g.pb(g.Mc(d));d=g.ld(g.Bc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.hd(c,g.bd(d));a.o.Hf(1)},
L6=function(a){a.Nx=(0,g.H)()+a.C;
CEa(a,a.C)},CEa=function(a,b){if(null!=a.Ol)throw Error("WatchDog timer not null");
a.Ol=S6((0,g.B)(a.nW,a),b)},T6=function(a){a.Ol&&(g.x.clearTimeout(a.Ol),a.Ol=null)},Q6=function(a){a.o.VA()||a.Oi||a.o.Lq(a)},P6=function(a){T6(a);
g.mf(a.dr);a.dr=null;a.A.stop();g.pn(a.Z);if(a.Xc){var b=a.Xc;a.Xc=null;b.abort();b.dispose()}a.Pf&&(a.Pf=null)},O6=function(a,b){try{a.o.KE(a,b),a.o.Hf(4)}catch(c){}},EEa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;DEa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){EEa(a,b,c,d,f)},f)})}},DEa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{U6(d),c(!0)}catch(e){}};
d.onerror=function(){try{U6(d),c(!1)}catch(e){}};
d.onabort=function(){try{U6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{U6(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},U6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},FEa=function(a){this.o=a;
this.A=new I6},GEa=function(a){var b=V6(a.o,a.Vl,"/mail/images/cleardot.gif");
l6(b);EEa(b.toString(),5E3,(0,g.B)(a.AK,a),3,2E3);a.Hf(1)},X6=function(a){var b=a.o.J;
if(null!=b)N6(5),b?(N6(11),W6(a.o,a,!1)):(N6(12),W6(a.o,a,!0));else if(a.Je=new J6(a,void 0,void 0,void 0),a.Je.dj=a.Xt,b=a.o,b=V6(b,b.Wn()?a.Nm:null,a.Yt),N6(5),!g.Id||g.tc(10))m6(b,"TYPE","xmlhttp"),K6(a.Je,b,!1,a.Nm,!1);else{m6(b,"TYPE","html");var c=a.Je;a=!!a.Nm;c.xk=3;c.Ph=l6(b.clone());BEa(c,a)}},Y6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new I6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},HEa=function(a,b){this.o=a;
this.map=b;this.context=null},IEa=function(a){g.pf.call(this,"statevent",a)},JEa=function(a,b){g.pf.call(this,"timingevent",a);
this.size=b},KEa=function(a){g.pf.call(this,"serverreachability",a)},NEa=function(a){LEa(a);
if(3==a.o){var b=a.In++,c=a.wp.clone();g.bn(c,"SID",a.B);g.bn(c,"RID",b);g.bn(c,"TYPE","terminate");Z6(a,c);b=new J6(a,a.B,b,void 0);b.xk=2;b.Ph=l6(c.clone());(new window.Image).src=b.Ph;b.wl=(0,g.H)();L6(b)}MEa(a)},OEa=function(a){a.WK(1,0);
a.wp=V6(a,null,a.Wt);$6(a)},LEa=function(a){a.Fh&&(a.Fh.abort(),a.Fh=null);
a.Bc&&(a.Bc.cancel(),a.Bc=null);a.Jg&&(g.x.clearTimeout(a.Jg),a.Jg=null);a7(a);a.ke&&(a.ke.cancel(),a.ke=null);a.Kh&&(g.x.clearTimeout(a.Kh),a.Kh=null)},PEa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new HEa(a.JR++,b));2!=a.o&&3!=a.o||$6(a)},$6=function(a){a.ke||a.Kh||(a.Kh=S6((0,g.B)(a.QE,a),0),a.lk=0)},REa=function(a,b){if(1==a.o){if(!b){a.In=Math.floor(1E5*Math.random());
var c=a.In++,d=new J6(a,"",c,void 0);d.dj=null;var e=b7(a),f=a.wp.clone();g.bn(f,"RID",c);g.bn(f,"CVER","1");Z6(a,f);wEa(d,f,e);a.ke=d;a.o=2}}else 3==a.o&&(b?QEa(a,b):0==a.A.length||a.ke||QEa(a))},QEa=function(a,b){if(b)if(6<a.Qi){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.In-1;var d=b7(a)}else c=b.G,d=b.Dj;else c=a.In++,d=b7(a);var e=a.wp.clone();g.bn(e,"SID",a.B);g.bn(e,"RID",c);g.bn(e,"AID",a.Nk);Z6(a,e);c=new J6(a,a.B,c,a.lk+1);c.dj=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ke=c;wEa(c,e,d)},Z6=function(a,b){if(a.Ed){var c=a.Ed.BA();
c&&g.Ib(c,function(a,c){g.bn(b,c,a)})}},b7=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.Qi&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.Qi?e:f-d;try{g.Ib(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},SEa=function(a){a.Bc||a.Jg||(a.G=1,a.Jg=S6((0,g.B)(a.PE,a),0),a.Yj=0)},c7=function(a){if(a.Bc||a.Jg||3<=a.Yj)return!1;
a.G++;a.Jg=S6((0,g.B)(a.PE,a),TEa(a,a.Yj));a.Yj++;return!0},W6=function(a,b,c){a.Sr=c;
a.gg=b.Zg;a.F||OEa(a)},a7=function(a){null!=a.Ri&&(g.x.clearTimeout(a.Ri),a.Ri=null)},TEa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},d7=function(a,b){if(2==b||9==b){var c=null;
a.Ed&&(c=null);var d=(0,g.B)(a.CX,a);c||(c=new g.Tm("//www.google.com/images/cleardot.gif"),l6(c));DEa(c.toString(),1E4,d)}else N6(2);UEa(a,b)},UEa=function(a,b){a.o=0;
a.Ed&&a.Ed.Cz(b);MEa(a);LEa(a)},MEa=function(a){a.o=0;
a.gg=-1;if(a.Ed)if(0==a.C.length&&0==a.A.length)a.Ed.Ts();else{g.Wa(a.C);var b=g.Wa(a.A);a.C.length=0;a.A.length=0;a.Ed.Ts(b)}},V6=function(a,b,c){var d=g.cn(c);
if(""!=d.A)b&&g.Vm(d,b+"."+d.A),g.Wm(d,d.D);else{var e=window.location;d=TDa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.tm&&g.Ib(a.tm,function(a,b){g.bn(d,b,a)});
g.bn(d,"VER",a.Qi);Z6(a,d);return d},S6=function(a,b){if(!g.za(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},N6=function(a){e7.dispatchEvent(new IEa(e7,a))},VEa=function(){},WEa=function(a,b){this.action=a;
this.params=b||{}},f7=function(a,b){g.L.call(this);
this.o=new g.U(this.OV,0,this);g.M(this,this.o);this.Fd=5E3;this.A=0;if(g.za(a))b&&(a=(0,g.B)(a,b));else if(a&&g.za(a.handleEvent))a=(0,g.B)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},g7=function(a,b,c){this.L=a;
this.F=b;this.B=new g.wD;this.A=new f7(this.kY,this);this.o=this.jb=null;this.K=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.N=c||!1},XEa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Sr,sessionId:a.o.B,arrayId:a.o.Nk}},YEa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&REa(a.o),NEa(a.o));a.H=0},h7=function(a){return!!a.o&&3==a.o.o},ZEa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},i7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Rg(a)||"";b&&(this.port=":"+b);this.domain=g.Qg(a)||"";a=g.Gb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.zb(a,"10.0")&&(this.A=!1))},j7=function(a,b){var c=a.o;
if(g.u(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.$g(c+b,{})},k7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Da(a.C,d,!0),onError:g.Da(a.B,e),Kd:g.Da(a.D,e)};c&&(a.Tb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.GE(b,a)},cFa=function(){var a=$Ea;
aFa();l7.push(a);bFa(l7)},m7=function(a,b){aFa();
var c=l7,d=dFa(a,String(b));g.Oa(c)?eFa(d):(bFa(c),(0,g.D)(c,function(a){a(d)}))},aFa=function(){l7||(l7=g.y("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",l7,void 0))},eFa=function(a){var b=(n7+1)%50;
n7=b;o7[b]=a;p7||(p7=49==b)},bFa=function(a){var b=o7;
if(b[0]){var c=n7,d=p7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.D)(a,function(a){a(e)})}while(d!=c);
o7=Array(50);n7=-1;p7=!1}},dFa=function(a,b){var c=((0,g.H)()-fFa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},q7=function(a){g.YF.call(this);
this.G=a;this.o=[]},gFa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},hFa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Wd)(a.o,function(a){return!!t6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=gFa(a,b[d])||c;return c},iFa=function(a,b){var c=a.o.length;
a.o=(0,g.Wd)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},r7=function(a,b,c,d){g.YF.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Fa=window.NaN},t7=function(a){q7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;s7(this);this.info("Initializing with "+r6(this.o))},jFa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=j7(a.B,"/pairing/get_lounge_token_batch");
k7(a.B,c,{screen_ids:b.join(",")},(0,g.B)(a.JL,a),(0,g.B)(a.IL,a))}},s7=function(a){var b=aEa(gEa());
b=(0,g.Wd)(b,function(a){return!a.uuid});
return hFa(a,b)},u7=function(a,b){iEa((0,g.I)(a.o,ZDa));
b&&hEa()},w7=function(a,b){g.YF.call(this);
this.F=b;var c=g.vH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Na(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;v7("Initialized with "+g.Ig(this.o))},kFa=function(a,b,c){var d=j7(a.D,"/pairing/get_screen_availability");
k7(a.D,d,{lounge_token:b.token},(0,g.B)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.B)(function(){c(!1)},a))},x7=function(a,b){a:if(g.Ob(b)!=g.Ob(a.o))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(v7("Updated online screens: "+g.Ig(a.o)),a.o=b,a.V("screenChange"));lFa(a)},y7=function(a){(0,window.isNaN)(a.B)||g.rE(a.B);
a.B=g.pE((0,g.B)(a.Pw,a),0<a.C&&a.C<(0,g.H)()?2E4:1E4)},v7=function(a){m7("OnlineScreenService",a)},mFa=function(a){var b={};
(0,g.D)(a.F(),function(a){a.token?b[a.token]=a.id:this.sc("Requesting availability of screen w/o lounge token.")});
return b},lFa=function(a){a=g.Rb(g.Jb(a.o,function(a){return a}));
g.fb(a);a.length?g.uH("yt-remote-online-screen-ids",a.join(","),60):g.wH("yt-remote-online-screen-ids")},z7=function(a){q7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};nFa(this)},pFa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.De();if(k=(c?u6(k,c):null)||u6(k,b)){k.uuid=b;var l=A7(a,k);kFa(a.A,l,function(a){e(a?l:null)})}else c?oFa(a,c,(0,g.B)(function(a){var f=A7(this,new o6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));kFa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},qFa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},oFa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Tb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.GE(j7(a.F,"/pairing/get_lounge_token_batch"),e)},rFa=function(a){a.o=a.B.De();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+r6(a.o))},nFa=function(a){B7(a);
a.B=new t7(a.F);a.B.subscribe("screenChange",(0,g.B)(a.XL,a));rFa(a);a.C=aEa(g.vH("yt-remote-automatic-screen-cache")||[]);B7(a);a.info("Initializing automatic screens: "+r6(a.C));a.A=new w7(a.F,(0,g.B)(a.De,a,!0));a.A.subscribe("screenChange",(0,g.B)(function(){this.V("onlineScreenChange")},a))},A7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=u6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.uH("yt-remote-automatic-screen-cache",(0,g.I)(a.C,ZDa)));B7(a);a.D[b.uuid]=b.id;g.uH("yt-remote-device-id-map",a.D,31536E3);return b},B7=function(a){a.D=g.vH("yt-remote-device-id-map")||{}},C7=function(a,b,c){g.YF.call(this);
this.N=c;this.J=a;this.A=b;this.B=null},D7=function(a,b){m7(a.N,b)},E7=function(a,b){C7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.B)(this.qY,this);this.D=(0,g.B)(this.zW,this);this.C=g.pE((0,g.B)(function(){sFa(this,null)},this),12E4)},tFa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Ig(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.A,(0,g.B)(function(){D7(this,"Failed to send message: getMdxSessionStatus.")},a)):D7(a,"Sending yt message without session: "+g.Ig(b))},sFa=function(a,b){g.rE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.B)(a.Mq,a),d=(0,g.B)(a.Ie,a);a.LA(b,c,d,5)}}else a.Ie(Error("Waiting for session status timed out."))},F7=function(a,b,c){C7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.O=c;this.D=null;this.G=g.A;this.F=window.NaN;this.L=(0,g.B)(this.tY,this);this.o=g.A},uFa=function(a){a.o=a.J.lH(a.K,a.A.label,a.A.friendlyName,(0,g.B)(function(a){this.o=g.A;
this.Mq(a)},a),(0,g.B)(function(a){this.o=g.A;
this.Ie(a)},a))},vFa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.O;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}kEa()&&(b.env_useStageMdx=1);return g.Yg(b)},G7=function(a,b){C7.call(this,a,b,"ManualSession");
this.o=g.pE((0,g.B)(this.Pk,this,null),150)},H7=function(a,b,c,d){g.YF.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.B)(this.ZU,this)},wFa=function(a,b){return b?g.Ja(a.B,function(a){return p6(b,a.label)},a):null},I7=function(a){m7("Controller",a)},$Ea=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},J7=function(a){return a.D||!!a.B.length||!!a.o},K7=function(a,b,c){b!=a.o&&(g.mf(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.B)(a.NE,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.Pk(null)):a.V("yt-remote-cast2-session-change",null))},xFa=function(a){var b=a.A.kH(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&p6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=wFa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},DFa=function(a,b,c,d,e,f,k){yFa()?zFa(b,e,f,k)&&(M7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?AFa(a,c):(window.__onGCastApiAvailable=function(b,d){b?AFa(a,c):(N7("Failed to load cast API: "+d),O7(!1),M7(!1),g.wH("yt-remote-cast-available"),g.wH("yt-remote-cast-receiver"),BFa(),
c(!1))},d?oEa():F6("CriOS")?tEa():F6("Android")&&F6("Chrome/")&&window.navigator.presentation?uEa():window.chrome&&window.navigator.presentation&&!F6("Edge")?(G6(),C6(CFa.map(rEa))):D6())):L7("Cannot initialize because not running Chrome")},BFa=function(){L7("dispose");
var a=P7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);EFa(!1);g.jG(Q7);Q7.length=0},R7=function(){return!!g.vH("yt-remote-cast-installed")},FFa=function(){var a=g.vH("yt-remote-cast-receiver");
return a?a.friendlyName:null},GFa=function(){L7("clearCurrentReceiver");
g.wH("yt-remote-cast-receiver")},HFa=function(){return R7()?P7()?P7().getCastSession():(N7("getCastSelector: Cast is not initialized."),null):(N7("getCastSelector: Cast API is not installed!"),null)},T7=function(){R7()?P7()?S7()?(L7("Requesting cast selector."),P7().requestSession()):(L7("Wait for cast API to be ready to request the session."),Q7.push(g.iG("yt-remote-cast2-api-ready",T7))):N7("requestCastSelector: Cast is not initialized."):N7("requestCastSelector: Cast API is not installed!")},U7=
function(a,b){S7()?P7().setConnectedScreenStatus(a,b):N7("setConnectedScreenStatus called before ready.")},yFa=function(){var a=0<=g.Gb.search(/ (CrMo|Chrome|CriOS)\//);
return g.MI||a},IFa=function(a,b){P7().init(a,b)},zFa=function(a,b,c,d){var e=!1;
P7()||(a=new H7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.uH("yt-remote-cast-available",a);g.mG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){L7("onReceiverSelected: "+a.friendlyName);
g.uH("yt-remote-cast-receiver",a);g.mG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){L7("onReceiverResumed: "+a.friendlyName);
g.uH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){L7("onSessionChange: "+q6(a));
a||g.wH("yt-remote-cast-receiver");g.mG("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
L7("cloudview.createSingleton_: "+e);return e},P7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},AFa=function(a,b){O7(!0);
M7(!1);IFa(a,function(a){a?(EFa(!0),g.lG("yt-remote-cast2-api-ready")):(N7("Failed to initialize cast API."),O7(!1),g.wH("yt-remote-cast-available"),g.wH("yt-remote-cast-receiver"),BFa());b(a)})},L7=function(a){m7("cloudview",a)},N7=function(a){m7("cloudview",a)},O7=function(a){L7("setCastInstalled_ "+a);
g.uH("yt-remote-cast-installed",a)},S7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},EFa=function(a){L7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},M7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},V7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.o=-1;this.muted=!1;this.audioTrackId=null;this.G=this.H=0;this.A=null;this.hasNext=this.kg=!1;this.K=this.J=this.B=this.D=0;this.C=window.NaN;this.F=!1;this.reset(a)},W7=function(a){a.audioTrackId=null;
a.A=null;a.o=-1;a.kg=!1;a.hasNext=!1;a.H=0;a.G=(0,g.H)();a.D=0;a.B=0;a.J=0;a.K=0;a.C=window.NaN;a.F=!1},X7=function(a){return a.sb()?((0,g.H)()-a.G)/1E3:0},Y7=function(a,b){a.H=b;
a.G=(0,g.H)()},Z7=function(a){switch(a.o){case 1:case 1081:return((0,g.H)()-a.G)/1E3+a.H;
case -1E3:return 0}return a.H},$7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&W7(a)},a8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.o;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.ec(a.A);b.hasPrevious=a.kg;b.hasNext=a.hasNext;b.playerTime=a.H;b.playerTimeAt=a.G;b.seekableStart=a.D;b.seekableEnd=a.B;b.duration=a.J;b.loadedTime=a.K;b.liveIngestionTime=a.C;return b},c8=function(a,b){g.YF.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.NC;this.B=this.A=null;this.J=(0,g.B)(this.sS,this);this.G=(0,g.B)(this.Ln,this);this.H=(0,g.B)(this.rS,this);this.K=(0,g.B)(this.ES,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ux,this),JFa(this))):c=3;0!=c&&(b?this.Ux(c):g.pE((0,g.B)(function(){this.Ux(c)},this),0));
var d=HFa();d&&b8(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},d8=function(a){return new V7(a.C.getPlayerContextData())},JFa=function(a){(0,g.D)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.Da(this.UU,a),this))},a)},KFa=function(a){(0,g.D)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},e8=function(a,b){50>a.D.Cc()&&g.PC(a.D,b)},g8=function(a,b,c){var d=d8(a);
Y7(d,c);-1E3!=d.o&&(d.o=b);f8(a,d)},h8=function(a,b,c){a.C.sendMessage(b,c)},f8=function(a,b){KFa(a);
a.C.setPlayerContextData(a8(b));JFa(a)},b8=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.Ln(null));
a.B=b;a.B&&(m7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.Ln(a.B.media[0]))},LFa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=d8(a);b.contentId!=d.videoId&&m7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.o=c.playerState;Y7(d,a.A.getEstimatedTime());f8(a,d)}else m7("CP","No cast media video. Ignoring state update.")},i8=function(a,b,c){return(0,g.B)(function(a){this.sc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.sc("Retrying "+b+" using MDx browser channel."),h8(this,b,c))},a)},j8=function(a,b,c){g.YF.call(this);
this.D=window.NaN;this.O=!1;this.K=this.J=this.L=this.N=window.NaN;this.W=[];this.C=this.G=this.B=this.kb=this.o=null;this.sa=a;this.W.push(g.HF(window,"beforeunload",(0,g.B)(this.zL,this)));this.A=[];this.kb=new V7;this.ca=b.id;this.o=MFa(this,c);this.o.subscribe("handlerOpened",this.wS,this);this.o.subscribe("handlerClosed",this.tS,this);this.o.subscribe("handlerError",this.uS,this);this.o.subscribe("handlerMessage",this.vS,this);ZEa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.kb.videoId;g.xH()&&g.uH("yt-remote-session-video-id",a)},this)},k8=function(a){m7("conn",a)},MFa=function(a,b){return new g7(j7(a.sa,"/bc"),b)},l8=function(a,b){a.V("proxyStateChange",b)},NFa=function(a){a.D=g.pE((0,g.B)(function(){k8("Connecting timeout");
this.F(1)},a),2E4)},m8=function(a){g.rE(a.D);
a.D=window.NaN},n8=function(a){g.rE(a.N);
a.N=window.NaN},OFa=function(a){o8(a);
a.L=g.pE((0,g.B)(function(){p8(this,"getNowPlaying")},a),2E4)},o8=function(a){g.rE(a.L);
a.L=window.NaN},QFa=function(a,b){b&&(m8(a),n8(a));
b==(h7(a.o)&&(0,window.isNaN)(a.D))?b&&(l8(a,1),p8(a,"getSubtitlesTrack")):b?(a.aa()&&a.kb.reset(),l8(a,1),p8(a,"getNowPlaying"),PFa(a)):a.F(1)},RFa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.kb.videoId&&(g.Zb(b.params)?a.kb.A=null:a.kb.A=b.params,a.V("remotePlayerChange"))},SFa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.kb.listId=b.params.listId||a.kb.listId;$7(a.kb,c,d);a.V("remoteQueueChange")},UFa=function(a,b){b.params=b.params||{};
SFa(a,b);TFa(a,b);a.V("autoplayDismissed")},TFa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
Y7(a.kb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.kb.o&&(c=-1E3);a.kb.o=c;c=Number(b.params.loadedTime);a.kb.K=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.kb.J=(0,window.isNaN)(c)?0:c;c=a.kb;var d=Number(b.params.liveIngestionTime);c.C=d;c.F=(0,window.isNaN)(d)?!1:!0;c=a.kb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.D=(0,window.isNaN)(d)?0:d;c.B=(0,window.isNaN)(e)?0:e;1==a.kb.o?OFa(a):o8(a);
a.V("remotePlayerChange")},VFa=function(a,b){if(-1E3!=a.kb.o){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.kb.o=c;c=(0,window.parseInt)(b.params.currentTime,10);Y7(a.kb,(0,window.isNaN)(c)?0:c);a.V("remotePlayerChange")}},WFa=function(a,b){var c="true"==b.params.muted;
a.kb.volume=(0,window.parseInt)(b.params.volume,10);a.kb.muted=c;a.V("remotePlayerChange")},XFa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},YFa=function(a,b){var c="true"==b.params.hasNext;
a.kb.kg="true"==b.params.hasPrevious;a.kb.hasNext=c;a.V("previousNextChange")},PFa=function(a){g.rE(a.K);
a.K=g.pE((0,g.B)(a.F,a,1),864E5)},p8=function(a,b,c){c?k8("Sending: action="+b+", params="+g.Ig(c)):k8("Sending: action="+b);
a.o.sendMessage(b,c)},q8=function(a){q7.call(this,"ScreenServiceProxy");
this.md=a;this.A=[];this.A.push(this.md.$_s("screenChange",(0,g.B)(this.oY,this)));this.A.push(this.md.$_s("onlineScreenChange",(0,g.B)(this.uU,this)))},cGa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.iE("MDX_CONFIG")||b;cEa();y6();r8||(r8=new i7(b?b.loungeApiHost:void 0),kEa()&&(r8.o="/api/loungedev"));s8||(s8=g.y("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",s8,void 0));ZFa();var c=t8();if(!c){var d=new z7(r8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=t8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);DFa(a,d,function(a){a?u8()&&U7(u8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.mG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),v8("Initializing: "+g.Ig(b)),w8.push(g.iG("yt-remote-cast2-availability-change",function(){g.mG("yt-remote-receiver-availability-change")})),w8.push(g.iG("yt-remote-cast2-receiver-selected",function(){x8(null);
g.mG("yt-remote-auto-connect","cast-selector-receiver")})),w8.push(g.iG("yt-remote-cast2-receiver-resumed",function(){g.mG("yt-remote-receiver-resumed","cast-selector-receiver")})),w8.push(g.iG("yt-remote-cast2-session-change",$Fa)),w8.push(g.iG("yt-remote-connection-change",function(a){a?U7(u8(),"YouTube TV"):y8()||(U7(null,null),GFa())})),a=z8(),b.isAuto&&(a.id+="#dial"),g.mE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),v8(" -- with channel params: "+
g.Ig(a)),aGa(a),c.start(),u8()||bGa())},eGa=function(){var a=dGa();
R7()&&g.vH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},dGa=function(){var a=t8().md.$_gos();
var b=A8();b&&B8()&&(t6(a,b)||a.push(b));return bEa(a)},C8=function(){var a=fGa();
!a&&R7()&&FFa()&&(a={key:"cast-selector-receiver",name:FFa()});return a},fGa=function(){var a=dGa(),b=A8();
b||(b=y8());return g.Ja(a,function(a){return b&&p6(b,a.key)?!0:!1})},A8=function(){var a=u8();
if(!a)return null;var b=t8().De();return u6(b,a)},$Fa=function(a){v8("remote.onCastSessionChange_: "+q6(a));
if(a){var b=A8();b&&b.id==a.id?U7(b.id,"YouTube TV"):(b&&D8(),E8(a,1))}else B8()&&D8()},D8=function(){S7()?P7().stopSession():N7("stopSession called before API ready.");
var a=B8();a&&(a.disconnect(1),F8(null))},G8=function(){var a=B8();
return!!a&&3!=a.getProxyState()},v8=function(a){m7("remote",a)},t8=function(){if(!H8){var a=g.y("yt.mdx.remote.screenService_");
H8=a?new q8(a):null}return H8},u8=function(){return g.y("yt.mdx.remote.currentScreenId_")},gGa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},hGa=function(){return g.y("yt.mdx.remote.connectData_")},x8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},B8=function(){return g.y("yt.mdx.remote.connection_")},F8=function(a){var b=B8();
x8(null);a||gGa("");g.ua("yt.mdx.remote.connection_",a,void 0);s8&&((0,g.D)(s8,function(b){b(a)}),s8.length=0);
b&&!a?g.mG("yt-remote-connection-change",!1):!b&&a&&g.mG("yt-remote-connection-change",!0)},y8=function(){var a=g.xH();
if(!a)return null;var b=t8().De();return u6(b,a)},E8=function(a,b){A8()&&A8();
gGa(a.id);var c=new j8(r8,a,z8());c.connect(b,hGa());c.subscribe("beforeDisconnect",function(a){g.mG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){B8()&&F8(null)});
F8(c)},bGa=function(){var a=y8();
a?(v8("Resume connection to: "+q6(a)),E8(a,0)):(z6(),GFa(),v8("Skipping connecting because no session screen found."))},ZFa=function(){var a=z8();
if(g.Zb(a)){a=x6();var b=g.vH("yt-remote-session-name")||"",c=g.vH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},z8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},aGa=function(a){a?(g.uH("yt-remote-session-app",a.app),g.uH("yt-remote-session-name",a.name)):(g.wH("yt-remote-session-app"),g.wH("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},I8=function(a,b,c){g.L.call(this);
this.C=a;this.T=b;this.A=new g.VF(this);g.M(this,this.A);this.A.R(b,"onCaptionsTrackListChanged",this.NT);this.A.R(b,"captionschanged",this.qS);this.A.R(b,"captionssettingschanged",this.sG);this.A.R(b,"videoplayerreset",this.Nq);this.A.R(b,"mdxautoplaycancel",this.zK);this.O=this.A.R(b,"onVolumeChange",this.tE);this.G=!1;this.o=c;c.subscribe("proxyStateChange",this.JE,this);c.subscribe("remotePlayerChange",this.Nn,this);c.subscribe("remoteQueueChange",this.Nq,this);c.subscribe("autoplayUpNext",this.fE,
this);c.subscribe("previousNextChange",this.GE,this);c.subscribe("nowAutoplaying",this.xE,this);c.subscribe("autoplayDismissed",this.eE,this);this.suggestion=null;this.H=new g.JP(64);this.B=new g.U(this.oG,500,this);g.M(this,this.B);this.D=new g.U(this.pG,1E3,this);g.M(this,this.D);this.K=new H6(this.PX,0,this);g.M(this,this.K);this.F={};this.L=new g.U(this.TG,1E3,this);g.M(this,this.L);this.J=new g.ul(this.uQ,1E3,this);g.M(this,this.J);this.N=g.A;this.sG();this.Nq();this.Nn()},J8=function(a,b){var c=
a.C,d=a.T.getVideoData().lengthSeconds;
c.J=b||0;c.player.V("progresssync",b,d)},iGa=function(a){J8(a,0);
a.B.stop();K8(a,new g.JP(64))},M8=function(a,b){if(L8(a)&&!a.G){var c=null;
b&&(c={style:a.T.wj()},g.gc(c,b));a.o.dG(a.T.getVideoData(1).videoId,c);a.F=d8(a.o).A}},N8=function(a,b){var c=a.T.rg();
if(c){var d=c.Be();var e=c.listId.toString()}var f=a.T.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.Gk;f=SDa(f);var n=d8(c);l=l||0;var p={videoId:k,currentIndex:l};$7(n,k,l);g.u(b)&&(Y7(n,b),p.currentTime=b);g.u(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Ig(f));h8(c,"setPlaylist",p);e||f8(c,n);K8(a,new g.JP(1))},jGa=function(a,b){if(b){var c=a.T.Fc("captions","tracklist",{EB:1});
c&&c.length?(a.T.Xd("captions","track",b),a.G=!1):(a.T.Xk("captions"),a.G=!0)}else a.T.Xd("captions","track",{})},L8=function(a){return d8(a.o).videoId==a.T.getVideoData(1).videoId},K8=function(a,b){a.D.stop();
var c=a.H;if(!g.PP(c,b)){var d=g.W(b,2);d!=g.W(a.H,2)&&g.ZT(a.T,d);a.H=b;kGa(a.C,c,b)}},O8=function(a){g.V.call(this,{I:"div",
M:"ytp-remote",P:[{I:"div",M:"ytp-remote-display-status",P:[{I:"div",M:"ytp-remote-display-status-icon",P:[g.tra()]},{I:"div",M:"ytp-remote-display-status-text",da:"{{statustext}}"}]}]});this.B=new g.YU(this,250);g.M(this,this.B);this.C=a;this.R(a,"presentingplayerstatechange",this.D);lGa(this,g.UT(a))},lGa=function(a,b){if(3==a.C.Sa()){var c={RECEIVER_NAME:a.C.Fc("remote","currentReceiver").name};
c=g.W(b,128)?g.QU("Error on $RECEIVER_NAME",c):b.sb()||g.W(b,4)?g.QU("Playing on $RECEIVER_NAME",c):g.QU("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},P8=function(a,b){g.wY.call(this,"Play on",0,a,b);
this.T=a;this.H={};this.R(a,"onMdxReceiversChange",this.K);this.R(a,"presentingplayerstatechange",this.K);this.K()},Q8=function(a){g.zU.call(this,a);
this.A={key:s6(),name:"This computer"};this.C=null;this.D=[];this.K=this.o=null;this.H=[this.A];this.B=this.A;this.F=new g.JP(64);this.J=0;this.G=-1;if(!g.kN(g.X(this.player))){a=this.player;var b=g.nI(a);b&&(b=b.Cn())&&(b=new P8(a,b),g.M(this,b));b=new O8(a);g.M(this,b);g.nU(a,b.element,4)}},kGa=function(a,b,c){a.F=c;
a.player.V("presentingplayerstatechange",new g.UP(c,b))},R8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)D8();
else{a.B=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.rg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.ab(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Gk,index:Math.max(a.player.JC(),0),currentTime:0==f?void 0:f};(d=SDa(d))&&(c.locationInfo=d);d=c}else d=null;v8("Connecting to: "+g.Ig(b));"cast-selector-receiver"==b.key?(x8(d||null),S7()?P7().setLaunchParams(d||
null):N7("setLaunchParams called before ready.")):!d&&G8()&&u8()==b.key?g.mG("yt-remote-connection-change",!0):(D8(),x8(d||null),d=t8().De(),(d=u6(d,b.key))&&E8(d,1))}},AEa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},R6={"'":"\\'"},mGa={},YDa={DZ:"atp",f4:"ska",x3:"que",J2:"mus",a4:"sus",N0:"dsp"};
n6.prototype.bp=function(){var a=new n6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var A6,w6="",E6=B6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",sEa=B6("loadCastFramework")||B6("loadCastApplicationFramework"),CFa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.C(H6,g.L);g.h=H6.prototype;g.h.uL=function(a){this.C=arguments;this.o=!1;this.Fa?this.B=(0,g.H)()+this.Fd:this.Fa=g.Dg(this.D,this.Fd)};
g.h.stop=function(){this.Fa&&(g.Eg(this.Fa),this.Fa=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.Y=function(){this.stop();H6.fa.Y.call(this)};
g.h.vL=function(){this.B?(this.Fa=g.Dg(this.D,this.B-(0,g.H)()),this.B=null):(this.Fa=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};I6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
I6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=J6.prototype;g.h.dj=null;g.h.Of=!1;g.h.Ol=null;g.h.Nx=null;g.h.wl=null;g.h.xk=null;g.h.Ph=null;g.h.si=null;g.h.Dj=null;g.h.Xc=null;g.h.eo=0;g.h.Pf=null;g.h.Ur=null;g.h.Qh=null;g.h.Om=-1;g.h.JF=!0;g.h.Oi=!1;g.h.Zt=0;g.h.dr=null;var yEa={},M6={};g.h=J6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.PW=function(a){a=a.target;var b=this.dr;b&&3==g.Ix(a)?b.Km():this.eH(a)};
g.h.eH=function(a){try{if(a==this.Xc)a:{var b=g.Ix(this.Xc),c=this.Xc.A,d=this.Xc.getStatus();if(g.Id&&!g.tc(10)||g.Kd&&!g.rc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.rf&&!g.Mx(this.Xc))break a;this.Oi||4!=b||7==c||(8==c||0>=d?this.o.Hf(3):this.o.Hf(2));T6(this);var e=this.Xc.getStatus();this.Om=e;var f=g.Mx(this.Xc);(this.Of=200==e)?(4==b&&P6(this),this.D?(zEa(this,b,f),g.rf&&this.Of&&3==b&&(this.Z.X(this.A,"tick",this.LW),this.A.start())):O6(this,f),this.Of&&!this.Oi&&(4==b?this.o.Lq(this):
(this.Of=!1,L6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Qh=3,N6(13)):(this.Qh=0,N6(14)),P6(this),Q6(this))}}catch(k){this.Xc&&g.Mx(this.Xc)}finally{}};
g.h.LW=function(){var a=g.Ix(this.Xc),b=g.Mx(this.Xc);this.eo<b.length&&(T6(this),zEa(this,a,b),this.Of&&4!=a&&L6(this))};
g.h.XV=function(a){S6((0,g.B)(this.WV,this,a),0)};
g.h.WV=function(a){this.Oi||(T6(this),O6(this,a),L6(this))};
g.h.SE=function(a){S6((0,g.B)(this.VV,this,a),0)};
g.h.VV=function(a){this.Oi||(P6(this),this.Of=a,this.o.Lq(this),this.o.Hf(4))};
g.h.cancel=function(){this.Oi=!0;P6(this)};
g.h.nW=function(){this.Ol=null;var a=(0,g.H)();0<=a-this.Nx?(2!=this.xk&&this.o.Hf(3),P6(this),this.Qh=2,N6(18),Q6(this)):CEa(this,this.Nx-a)};g.h=FEa.prototype;g.h.Xt=null;g.h.Je=null;g.h.fr=!1;g.h.WA=null;g.h.rp=null;g.h.Su=null;g.h.Yt=null;g.h.df=null;g.h.Zg=-1;g.h.Nm=null;g.h.Vl=null;g.h.connect=function(a){this.Yt=a;a=V6(this.o,null,this.Yt);N6(3);this.WA=(0,g.H)();var b=this.o.H;null!=b?(this.Nm=b[0],(this.Vl=b[1])?(this.df=1,GEa(this)):(this.df=2,X6(this))):(m6(a,"MODE","init"),this.Je=new J6(this,void 0,void 0,void 0),this.Je.dj=this.Xt,K6(this.Je,a,!1,null,!0),this.df=0)};
g.h.AK=function(a){if(a)this.df=2,X6(this);else{N6(4);var b=this.o;b.gg=b.Fh.Zg;d7(b,9)}a&&this.Hf(2)};
g.h.qt=function(a){return this.o.qt(a)};
g.h.abort=function(){this.Je&&(this.Je.cancel(),this.Je=null);this.Zg=-1};
g.h.VA=function(){return!1};
g.h.KE=function(a,b){this.Zg=a.Om;if(0==this.df)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.gg=this.Zg;d7(c,2);return}this.Nm=c[0];this.Vl=c[1]}else c=this.o,c.gg=this.Zg,d7(c,2);else if(2==this.df)if(this.fr)N6(7),this.Su=(0,g.H)();else if("11111"==b){if(N6(6),this.fr=!0,this.rp=(0,g.H)(),c=this.rp-this.WA,!g.Id||g.tc(10)||500>c)this.Zg=200,this.Je.cancel(),N6(12),W6(this.o,this,!0)}else N6(8),this.rp=this.Su=(0,g.H)(),this.fr=!1};
g.h.Lq=function(){this.Zg=this.Je.Om;if(this.Je.Of)0==this.df?this.Vl?(this.df=1,GEa(this)):(this.df=2,X6(this)):2==this.df&&((!g.Id||g.tc(10)?!this.fr:200>this.Su-this.rp)?(N6(11),W6(this.o,this,!1)):(N6(12),W6(this.o,this,!0)));else{0==this.df?N6(9):2==this.df&&N6(10);var a=this.o;a.gg=this.Zg;d7(a,2)}};
g.h.Wn=function(){return this.o.Wn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Hf=function(a){this.o.Hf(a)};g.h=Y6.prototype;g.h.tm=null;g.h.ke=null;g.h.Bc=null;g.h.Wt=null;g.h.wp=null;g.h.qz=null;g.h.Jp=null;g.h.In=0;g.h.JR=0;g.h.Ed=null;g.h.Kh=null;g.h.Jg=null;g.h.Ri=null;g.h.Fh=null;g.h.Sr=null;g.h.Nk=-1;g.h.SB=-1;g.h.gg=-1;g.h.lk=0;g.h.Yj=0;g.h.Qi=8;var e7=new g.Qf;g.C(IEa,g.pf);g.C(JEa,g.pf);g.C(KEa,g.pf);g.h=Y6.prototype;g.h.connect=function(a,b,c,d,e){N6(0);this.Wt=b;this.tm=c||{};d&&g.u(e)&&(this.tm.OSID=d,this.tm.OAID=e);this.F?(S6((0,g.B)(this.Mz,this,a),100),OEa(this)):this.Mz(a)};
g.h.Mz=function(a){this.Fh=new FEa(this);this.Fh.Xt=null;this.Fh.A=this.D;this.Fh.connect(a)};
g.h.VA=function(){return 0==this.o};
g.h.QE=function(a){this.Kh=null;REa(this,a)};
g.h.PE=function(){this.Jg=null;this.Bc=new J6(this,this.B,"rpc",this.G);this.Bc.dj=null;this.Bc.Zt=0;var a=this.qz.clone();g.bn(a,"RID","rpc");g.bn(a,"SID",this.B);g.bn(a,"CI",this.Sr?"0":"1");g.bn(a,"AID",this.Nk);Z6(this,a);if(!g.Id||g.tc(10))g.bn(a,"TYPE","xmlhttp"),K6(this.Bc,a,!0,this.Jp,!1);else{g.bn(a,"TYPE","html");var b=this.Bc,c=!!this.Jp;b.xk=3;b.Ph=l6(a.clone());BEa(b,c)}};
g.h.KE=function(a,b){if(0!=this.o&&(this.Bc==a||this.ke==a))if(this.gg=a.Om,this.ke==a&&3==this.o)if(7<this.Qi){try{var c=this.D.parse(b)}catch(f){c=null}if(g.xa(c)&&3==c.length)if(0==c[0])a:{if(!this.Jg){if(this.Bc)if(this.Bc.wl+3E3<this.ke.wl)a7(this),this.Bc.cancel(),this.Bc=null;else break a;c7(this);N6(19)}}else this.SB=c[1],0<this.SB-this.Nk&&37500>c[2]&&this.Sr&&0==this.Yj&&!this.Ri&&(this.Ri=S6((0,g.B)(this.lS,this),6E3));else d7(this,11)}else b!=mGa.E_.o&&d7(this,11);else if(this.Bc==a&&
a7(this),!g.F(b)){c=this.D.parse(b);g.xa(c);for(var d=0;d<c.length;d++){var e=c[d];this.Nk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.Jp=e[2],e=e[3],null!=e?this.Qi=e:this.Qi=6,this.o=3,this.Ed&&this.Ed.Ez(),this.qz=V6(this,this.Wn()?this.Jp:null,this.Wt),SEa(this)):"stop"==e[0]&&d7(this,7):3==this.o&&("stop"==e[0]?d7(this,7):"noop"!=e[0]&&this.Ed&&this.Ed.Dz(e),this.Yj=0)}}};
g.h.lS=function(){null!=this.Ri&&(this.Ri=null,this.Bc.cancel(),this.Bc=null,c7(this),N6(20))};
g.h.Lq=function(a){if(this.Bc==a){a7(this);this.Bc=null;var b=2}else if(this.ke==a)this.ke=null,b=1;else return;this.gg=a.Om;if(0!=this.o)if(a.Of)1==b?(b=(0,g.H)()-a.wl,e7.dispatchEvent(new JEa(e7,a.Dj?a.Dj.length:0,b,this.lk)),$6(this),this.C.length=0):SEa(this);else{var c=a.Qh,d;if(!(d=3==c||7==c||0==c&&0<this.gg)){if(d=1==b)this.ke||this.Kh||1==this.o||2<=this.lk?d=!1:(this.Kh=S6((0,g.B)(this.QE,this,a),TEa(this,this.lk)),this.lk++,d=!0);d=!(d||2==b&&c7(this))}if(d)switch(c){case 1:d7(this,5);
break;case 4:d7(this,10);break;case 3:d7(this,6);break;case 7:d7(this,12);break;default:d7(this,2)}}};
g.h.WK=function(a){if(!g.Na(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.CX=function(a){a?N6(2):(N6(1),UEa(this,8))};
g.h.qt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Cx;a.H=!1;return a};
g.h.isActive=function(){return!!this.Ed&&this.Ed.isActive(this)};
g.h.Hf=function(a){e7.dispatchEvent(new KEa(e7,a))};
g.h.Wn=function(){return!(!g.Id||g.tc(10))};
g.h=VEa.prototype;g.h.Ez=function(){};
g.h.Dz=function(){};
g.h.Cz=function(){};
g.h.Ts=function(){};
g.h.BA=function(){return{}};
g.h.isActive=function(){return!0};g.C(f7,g.L);g.h=f7.prototype;g.h.OV=function(){this.Fd=Math.min(3E5,2*this.Fd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Fd+15E3*Math.random();g.Bu(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Fd=5E3};g.C(g7,VEa);g.h=g7.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.ce=function(a){return this.B.ce(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.mf(this.B),YEa(this),g.mf(this.A),this.A=null)};
g.h.la=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new Y6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.N),e=this.o;e&&(e.Ed=null);d.Ed=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.Nk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.gc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):h7(this)&&PEa(this.o,c)};
g.h.Ez=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)PEa(this.o,a[b])}this.V("handlerOpened")};
g.h.Cz=function(a){var b=2==a&&401==this.o.gg;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.Ts=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.BA=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.gc(a,this.D);return a};
g.h.Dz=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),NEa(this.o)):this.V("handlerMessage",new WEa(a[0],a[1]))};
g.h.kY=function(){this.A.isActive();var a=this.o,b=0;a.Bc&&b++;a.ke&&b++;0!=b||this.connect(this.D,this.C)};i7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
i7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
i7.prototype.D=function(a){a(Error("request timed out"))};var fFa=(0,g.H)(),l7=null,o7=Array(50),n7=-1,p7=!1;g.C(q7,g.YF);q7.prototype.De=function(){return this.o};
q7.prototype.contains=function(a){return!!t6(this.o,a)};
q7.prototype.get=function(a){return a?u6(this.o,a):null};
q7.prototype.info=function(a){m7(this.G,a)};g.C(r7,g.YF);var nGa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=r7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Fa)&&this.jH()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Fa)||(g.rE(this.Fa),this.Fa=window.NaN)};
g.h.Y=function(){this.stop();r7.fa.Y.call(this)};
g.h.jH=function(){this.Fa=window.NaN;this.o=g.GE(j7(this.F,"/pairing/get_screen"),{method:"POST",Tb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.B)(this.mY,this),onError:(0,g.B)(this.lY,this),Kd:(0,g.B)(this.nY,this)})};
g.h.mY=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new o6(c))};
g.h.lY=function(a){this.o=null;a.status&&404==a.status?this.A>=nGa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=nGa[this.A],this.Fa=g.pE((0,g.B)(this.jH,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.nY=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.C(t7,q7);g.h=t7.prototype;g.h.start=function(){s7(this)&&this.V("screenChange");!g.vH("yt-remote-lounge-token-expiration")&&jFa(this);g.rE(this.A);this.A=g.pE((0,g.B)(this.start,this),1E4)};
g.h.add=function(a,b){s7(this);gFa(this,a);u7(this,!1);this.V("screenChange");b(a);a.token||jFa(this)};
g.h.remove=function(a,b){var c=s7(this);iFa(this,a)&&(u7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.Nr=function(a,b,c,d){var e=s7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,u7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.Y=function(){g.rE(this.A);t7.fa.Y.call(this)};
g.h.JL=function(a){s7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}u7(this,!b);b&&m7(this.G,"Missed "+b+" lounge tokens.")};
g.h.IL=function(a){m7(this.G,"Requesting lounge tokens failed: "+a)};g.C(w7,g.YF);g.h=w7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.vH("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.H)()-144E5<a?0:a)?y7(this):(this.C=(0,g.H)()+3E5,g.uH("yt-remote-fast-check-period",this.C),this.Pw())};
g.h.isEmpty=function(){return g.Zb(this.o)};
g.h.update=function(){v7("Updating availability on schedule.");var a=this.F(),b=g.Jb(this.o,function(b,d){return b&&!!u6(a,d)},this);
x7(this,b)};
g.h.Y=function(){g.rE(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);w7.fa.Y.call(this)};
g.h.Pw=function(){g.rE(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=mFa(this);if(g.Ob(a)){var b=j7(this.D,"/pairing/get_screen_availability");this.A=k7(this.D,b,{lounge_token:g.Rb(a).join(",")},(0,g.B)(this.vV,this,a),(0,g.B)(this.uV,this))}else x7(this,{}),y7(this)};
g.h.vV=function(a,b){this.A=null;var c=g.Rb(mFa(this));if(g.gb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;x7(this,d);y7(this)}else this.sc("Changing Screen set during request."),this.Pw()};
g.h.uV=function(a){this.sc("Screen availability failed: "+a);this.A=null;y7(this)};
g.h.sc=function(a){m7("OnlineScreenService",a)};g.C(z7,q7);g.h=z7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.Nr=function(a,b,c,d){this.B.contains(a)?this.B.Nr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,m7(this.G,a),d(Error(a)))};
g.h.De=function(a){return a?this.o:g.Va(this.o,(0,g.Wd)(this.C,function(a){return!this.contains(a)},this))};
g.h.kH=function(){return(0,g.Wd)(this.De(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.lH=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new r7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.B)(function(a){g.mf(f);d(A7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.mf(f);e(a)});
f.start();return(0,g.B)(f.stop,f)};
g.h.pY=function(a,b,c,d){g.GE(j7(this.F,"/pairing/get_screen"),{method:"POST",Tb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.B)(function(a,d){var e=new o6(d.screen||{});if(!e.name||qFa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);qFa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(A7(this,e))},this),
onError:(0,g.B)(function(a){d(Error("pairing request failed: "+a.status))},this),
Kd:(0,g.B)(function(){d(Error("pairing request timed out."))},this)})};
g.h.Y=function(){g.mf(this.B);g.mf(this.A);z7.fa.Y.call(this)};
g.h.XL=function(){rFa(this);this.V("screenChange");this.A.update()};
z7.prototype.dispose=z7.prototype.dispose;g.C(C7,g.YF);g.h=C7.prototype;g.h.Mq=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.Ie=function(a){this.la()||(a&&D7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){m7(this.N,a)};
g.h.nH=function(){return null};
g.h.Xw=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.B)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.B)(function(){D7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.Y=function(){this.Xw("");C7.fa.Y.call(this)};g.C(E7,C7);g.h=E7.prototype;g.h.Ww=function(a){if(this.o){if(this.o==a)return;D7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);tFa(this)};
g.h.Pk=function(a){this.info("launchWithParams no-op for Cast: "+g.Ig(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.B)(function(){this.Ie()},this),(0,g.B)(function(){this.Ie(Error("Failed to stop receiver app."))},this)):this.Ie(Error("Stopping cast device witout session."))};
g.h.Xw=g.A;g.h.Y=function(){this.info("disposeInternal");g.rE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;E7.fa.Y.call(this)};
g.h.zW=function(a,b){if(!this.la())if(b){var c=g.wx(b);if(g.Aa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Ig(c));switch(d){case "mdxSessionStatus":sFa(this,c.screenId);break;default:D7(this,"Unknown youtube message: "+d)}}else D7(this,"Unable to parse message.")}else D7(this,"No data in message.")};
g.h.LA=function(a,b,c,d){pFa(this.J,this.A.label,a,this.A.friendlyName,(0,g.B)(function(e){e?b(e):0<=d?(D7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.pE((0,g.B)(this.LA,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.nH=function(){return this.o};
g.h.qY=function(a){this.la()||a||(D7(this,"Cast session died."),this.Ie())};g.C(F7,C7);g.h=F7.prototype;g.h.Ww=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.Pk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.A;g.rE(this.F);this.C?this.C.stop((0,g.B)(this.Ie,this,null),(0,g.B)(this.Ie,this,"Failed to stop DIAL device.")):this.Ie()};
g.h.Y=function(){this.o();this.o=g.A;g.rE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;F7.fa.Y.call(this)};
g.h.tY=function(a){this.la()||a||(D7(this,"DIAL session died."),this.o(),this.o=g.A,this.Ie())};
g.h.Du=function(a){this.K=s6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,vFa(this));a(b);uFa(this)}else this.G=(0,g.B)(function(){g.rE(this.F);this.G=g.A;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,vFa(this));a(b);uFa(this)},this),this.F=g.pE((0,g.B)(function(){this.G()},this),100)};
g.h.nN=function(a,b,c){pFa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.B)(function(a){a&&a.token?(this.Mq(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Du(b,c)},this),(0,g.B)(function(a){D7(this,"Failed to get DIAL screen: "+a);
this.Du(b,c)},this))};g.C(G7,C7);G7.prototype.stop=function(){this.Ie()};
G7.prototype.Ww=g.A;G7.prototype.Pk=function(){g.rE(this.o);this.o=window.NaN;var a=u6(this.J.De(),this.A.label);a?this.Mq(a):this.Ie(Error("No such screen"))};
G7.prototype.Y=function(){g.rE(this.o);this.o=window.NaN;G7.fa.Y.call(this)};g.C(H7,g.YF);g.h=H7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.B)(this.ME,this),(0,g.B)(this.dV,this),d,e);c.customDialLaunchCallback=(0,g.B)(this.WS,this);window.chrome.cast.initialize(c,
(0,g.B)(function(){this.la()||(window.chrome.cast.addReceiverActionListener(this.C),cFa(),this.A.subscribe("onlineScreenChange",(0,g.B)(this.mH,this)),this.B=xFa(this),window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(a){this.sc("Failed to set initial custom receivers: "+g.Ig(a))},this)),this.V("yt-remote-cast2-availability-change",J7(this)),b(!0))},this),(0,g.B)(function(a){this.sc("Failed to initialize API: "+g.Ig(a));
b(!1)},this))};
g.h.kX=function(a,b){I7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)I7("Unsetting old screen status: "+this.o.A.friendlyName),K7(this,null)}if(a&&b){if(!this.o){c=u6(this.A.De(),a);if(!c){I7("setConnectedScreenStatus: Unknown screen.");return}var d=wFa(this,c);d||(I7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(a){this.sc("Failed to set initial custom receivers: "+g.Ig(a))},this)));
I7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);K7(this,new G7(this.A,d),!0)}this.o.Xw(b)}else I7("setConnectedScreenStatus: no screen.")};
g.h.lX=function(a){this.la()?this.sc("Setting connection data on disposed cast v2"):this.o?this.o.Pk(a):this.sc("Setting connection data without a session")};
g.h.sY=function(){this.la()?this.sc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),K7(this,null)):I7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.B)(this.ME,this),(0,g.B)(this.zV,this))};
g.h.Y=function(){this.A.unsubscribe("onlineScreenChange",(0,g.B)(this.mH,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.Ta(g.y("yt.mdx.remote.debug.handlers_")||[],$Ea);g.mf(this.o);H7.fa.Y.call(this)};
g.h.sc=function(a){m7("Controller",a)};
g.h.NE=function(a,b){this.o==a&&(b||K7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.ZU=function(a,b){if(!this.la())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),I7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)I7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{I7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:K7(this,
new G7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:K7(this,new F7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:K7(this,new E7(this.A,a));break;default:this.sc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.sc("Stopping receiver w/o session: "+a.friendlyName)}else this.sc("onReceiverAction_ called without receiver.")};
g.h.WS=function(a){if(this.la())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.sc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.sc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return I7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.sc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);K7(this,new F7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.B)(b.nN,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.B)(b.Du,b))};
g.h.ME=function(a){if(!this.la()){I7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)I7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),K7(this,new E7(this.A,b),!0);else{this.sc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=u6(this.A.De(),c.label);
d&&p6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(I7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.mf(this.o),this.o=new E7(this.A,b),this.o.subscribe("sessionScreen",(0,g.B)(this.NE,this,this.o)),this.o.Pk(null));this.o.Ww(a)}}};
g.h.rY=function(){return this.o?this.o.nH():null};
g.h.zV=function(a){this.la()||(this.sc("Failed to estabilish a session: "+g.Ig(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&K7(this,null))};
g.h.dV=function(a){I7("Receiver availability updated: "+a);if(!this.la()){var b=J7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;J7(this)!=b&&this.V("yt-remote-cast2-availability-change",J7(this))}};
g.h.mH=function(){this.la()||(this.B=xFa(this),I7("Updating custom receivers: "+g.Ig(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(){this.sc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",J7(this)))};
H7.prototype.setLaunchParams=H7.prototype.lX;H7.prototype.setConnectedScreenStatus=H7.prototype.kX;H7.prototype.stopSession=H7.prototype.sY;H7.prototype.getCastSession=H7.prototype.rY;H7.prototype.requestSession=H7.prototype.requestSession;H7.prototype.init=H7.prototype.init;H7.prototype.dispose=H7.prototype.dispose;var Q7=[];g.h=V7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";W7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.o=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.A=a.trackData,this.kg=a.hasPrevious,this.hasNext=a.hasNext,this.H=a.playerTime,this.G=a.playerTimeAt,this.D=a.seekableStart,this.B=a.seekableEnd,this.J=a.duration,this.K=a.loadedTime,this.C=a.liveIngestionTime,this.F=!(0,window.isNaN)(this.C))};
g.h.sb=function(){return 1==this.o};
g.h.isAdPlaying=function(){return 1081==this.o};
g.h.getDuration=function(){return this.F?this.J+X7(this):this.J};
g.h.clone=function(){return new V7(a8(this))};g.C(c8,g.YF);g.h=c8.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.A,i8(this,"play")):h8(this,"play"),g8(this,1,Z7(d8(this))),this.V("remotePlayerChange")):e8(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.A,i8(this,"pause")):h8(this,"pause"),g8(this,2,Z7(d8(this))),this.V("remotePlayerChange")):e8(this,this.pause)};
g.h.iH=function(a){if(1==this.o){if(this.A){var b=d8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.sb()||3==b.o?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.A,i8(this,"seekTo",{newTime:a}))}else h8(this,"seekTo",{newTime:a});g8(this,3,a);this.V("remotePlayerChange")}else e8(this,g.Da(this.iH,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.A,i8(this,"stopVideo")):h8(this,"stopVideo");var a=d8(this);a.index=-1;a.videoId="";W7(a);f8(this,a);this.V("remotePlayerChange")}else e8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=d8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.B)(function(){m7("CP","set receiver volume: "+d)},this),(0,g.B)(function(){this.sc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.B)(function(){m7("CP","set receiver muted: "+b)},this),(0,g.B)(function(){this.sc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);h8(this,"setVolume",e)}c.muted=b;c.volume=a;f8(this,c)}else e8(this,g.Da(this.setVolume,a,b))};
g.h.dG=function(a,b){if(1==this.o){var c=d8(this),d={videoId:a};b&&(c.A={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Ig(b.style),g.gc(d,c.A));h8(this,"setSubtitlesTrack",d);f8(this,c)}else e8(this,g.Da(this.dG,a,b))};
g.h.Tx=function(a,b){if(1==this.o){h8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Mb.id});var c=d8(this);c.audioTrackId=b.Mb.id;f8(this,c)}else e8(this,g.Da(this.Tx,a,b))};
g.h.hH=function(a,b){if(1==this.o){if(a&&b){var c=d8(this);$7(c,a,b);f8(this,c)}h8(this,"previous")}else e8(this,g.Da(this.hH,a,b))};
g.h.gH=function(a,b){if(1==this.o){if(a&&b){var c=d8(this);$7(c,a,b);f8(this,c)}h8(this,"next")}else e8(this,g.Da(this.gH,a,b))};
g.h.fA=function(){1==this.o?h8(this,"dismissAutoplay"):e8(this,this.fA)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}c8.fa.dispose.call(this)};
g.h.Y=function(){KFa(this);this.C=null;this.D.clear();b8(this,null);c8.fa.Y.call(this)};
g.h.Ux=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.QC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.UU=function(a,b){this.V(a,b)};
g.h.sS=function(a){if(!a)this.Ln(null),b8(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=d8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)m7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,f8(this,b)}};
g.h.Ln=function(a){m7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),LFa(this),this.V("remotePlayerChange")};
g.h.rS=function(a){a?(LFa(this),this.V("remotePlayerChange")):this.Ln(null)};
g.h.ES=function(){var a=HFa();a&&b8(this,a)};
g.h.sc=function(a){m7("CP",a)};g.C(j8,g.YF);g.h=j8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.kb.listId=c);this.kb.videoId=d;this.kb.index=k||0;this.kb.state=3;Y7(this.kb,m);this.C="UNSUPPORTED";k8("Connecting with setPlaylist and params: "+g.Ig(l));this.o.connect({method:"setPlaylist",
params:g.Ig(l)},a,fEa())}else k8("Connecting without params"),this.o.connect({},a,fEa());NFa(this)};
g.h.dispose=function(){this.la()||(this.V("beforeDispose"),l8(this,3));j8.fa.dispose.call(this)};
g.h.Y=function(){m8(this);o8(this);n8(this);g.rE(this.J);this.J=window.NaN;g.rE(this.K);this.K=window.NaN;this.B=null;g.IF(this.W);this.W.length=0;this.o.dispose();j8.fa.Y.call(this);this.C=this.G=this.A=this.kb=this.o=null};
g.h.zL=function(){this.F(2)};
g.h.wS=function(){k8("Channel opened");this.O&&(this.O=!1,n8(this),this.N=g.pE((0,g.B)(function(){k8("Timing out waiting for a screen.");this.F(1)},this),15E3));
jEa(XEa(this.o),this.ca)};
g.h.tS=function(){k8("Channel closed");(0,window.isNaN)(this.D)?z6(!0):z6();this.dispose()};
g.h.uS=function(a){z6();(0,window.isNaN)(this.H())?(k8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,k8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),l8(this,2))};
g.h.vS=function(a){a.params?k8("Received: action="+a.action+", params="+g.Ig(a.params)):k8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.wx(a.params.devices);this.A=(0,g.I)(a,function(a){return new n6(a)});
a=!!g.Ja(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
QFa(this,a);break;case "loungeScreenDisconnected":g.Ua(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
QFa(this,!1);break;case "remoteConnected":var b=new n6(g.wx(a.params.device));g.Ja(this.A,function(a){return b?a.id==b.id:!1})||g.Ra(this.A,b);
break;case "remoteDisconnected":b=new n6(g.wx(a.params.device));g.Ua(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":SFa(this,a);break;case "nowPlaying":UFa(this,a);break;case "onStateChange":TFa(this,a);break;case "onAdStateChange":VFa(this,a);break;case "onVolumeChanged":WFa(this,a);break;case "onSubtitlesTrackChanged":RFa(this,a);break;case "nowAutoplaying":XFa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":YFa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:k8("Unrecognized action: "+a.action)}};
g.h.XW=function(){if(this.B){var a=this.B;this.B=null;this.kb.videoId!=a&&p8(this,"getNowPlaying")}};
j8.prototype.subscribe=j8.prototype.subscribe;j8.prototype.unsubscribeByKey=j8.prototype.ce;j8.prototype.ia=function(){var a=3;this.la()||(a=0,(0,window.isNaN)(this.H())?h7(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
j8.prototype.getProxyState=j8.prototype.ia;j8.prototype.F=function(a){k8("Disconnecting with "+a);m8(this);this.V("beforeDisconnect",a);1==a&&z6();YEa(this.o,a);this.dispose()};
j8.prototype.disconnect=j8.prototype.F;j8.prototype.ha=function(){var a=this.kb;this.B&&(a=this.kb.clone(),$7(a,this.B,a.index));return a8(a)};
j8.prototype.getPlayerContextData=j8.prototype.ha;
j8.prototype.pa=function(a){var b=new V7(a);b.videoId&&b.videoId!=this.kb.videoId&&(this.B=b.videoId,g.rE(this.J),this.J=g.pE((0,g.B)(this.XW,this),5E3));var c=[];this.kb.listId==b.listId&&this.kb.videoId==b.videoId&&this.kb.index==b.index||c.push("remoteQueueChange");this.kb.o==b.o&&this.kb.volume==b.volume&&this.kb.muted==b.muted&&Z7(this.kb)==Z7(b)&&g.Ig(this.kb.A)==g.Ig(b.A)||c.push("remotePlayerChange");this.kb.reset(a);(0,g.D)(c,function(a){this.V(a)},this)};
j8.prototype.setPlayerContextData=j8.prototype.pa;j8.prototype.aa=function(){var a=this.o.F.id,b=g.Ja(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
j8.prototype.getOtherConnectedRemoteId=j8.prototype.aa;j8.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():window.NaN};
j8.prototype.getReconnectTimeout=j8.prototype.H;j8.prototype.ba=function(){return this.C||"UNSUPPORTED"};
j8.prototype.getAutoplayMode=j8.prototype.ba;j8.prototype.ga=function(){return this.G||""};
j8.prototype.getAutoplayVideoId=j8.prototype.ga;j8.prototype.wa=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.Cu(a.o);a.start()}};
j8.prototype.reconnect=j8.prototype.wa;j8.prototype.ka=function(a,b){p8(this,a,b);PFa(this)};
j8.prototype.sendMessage=j8.prototype.ka;g.C(q8,q7);g.h=q8.prototype;g.h.De=function(a){return this.md.$_gs(a)};
g.h.contains=function(a){return!!this.md.$_c(a)};
g.h.get=function(a){return this.md.$_g(a)};
g.h.start=function(){this.md.$_st()};
g.h.add=function(a,b,c){this.md.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.md.$_r(a,b,c)};
g.h.Nr=function(a,b,c,d){this.md.$_un(a,b,c,d)};
g.h.Y=function(){for(var a=0,b=this.A.length;a<b;++a)this.md.$_ubk(this.A[a]);this.A.length=0;this.md=null;q8.fa.Y.call(this)};
g.h.oY=function(){this.V("screenChange")};
g.h.uU=function(){this.V("onlineScreenChange")};
z7.prototype.$_st=z7.prototype.start;z7.prototype.$_gspc=z7.prototype.pY;z7.prototype.$_gsppc=z7.prototype.lH;z7.prototype.$_c=z7.prototype.contains;z7.prototype.$_g=z7.prototype.get;z7.prototype.$_a=z7.prototype.add;z7.prototype.$_un=z7.prototype.Nr;z7.prototype.$_r=z7.prototype.remove;z7.prototype.$_gs=z7.prototype.De;z7.prototype.$_gos=z7.prototype.kH;z7.prototype.$_s=z7.prototype.subscribe;z7.prototype.$_ubk=z7.prototype.ce;var r8=null,s8=null,H8=null,w8=[];g.t(I8,g.L);g.h=I8.prototype;
g.h.Y=function(){g.L.prototype.Y.call(this);this.B.stop();this.D.stop();this.K.stop();this.N();this.o.unsubscribe("proxyStateChange",this.JE,this);this.o.unsubscribe("remotePlayerChange",this.Nn,this);this.o.unsubscribe("remoteQueueChange",this.Nq,this);this.o.unsubscribe("autoplayUpNext",this.fE,this);this.o.unsubscribe("previousNextChange",this.GE,this);this.o.unsubscribe("nowAutoplaying",this.xE,this);this.o.unsubscribe("autoplayDismissed",this.eE,this);this.o=this.C=null};
g.h.cD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(L8(this)){if(!d8(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":d8(this.o).sb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.J.Km(c[0],c[1]);break;case "control_subtitles_set_track":M8(this,c[0]);break;case "control_set_audio_track":c=c[0],L8(this)&&this.o.Tx(this.T.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.T.getCurrentTime();N8(this,0==c?void 0:c);break;case "control_seek":N8(this,c[0]);break;case "control_subtitles_set_track":M8(this,c[0]);break;case "control_set_audio_track":c=c[0],L8(this)&&this.o.Tx(this.T.getVideoData(1).videoId,c)}};
g.h.qS=function(a){this.K.uL(a)};
g.h.PX=function(a){this.cD("control_subtitles_set_track",g.Zb(a)?null:a)};
g.h.sG=function(){var a=this.T.Fc("captions","track");g.Zb(a)||M8(this,a)};
g.h.tE=function(a){if(L8(this)){this.o.unsubscribe("remotePlayerChange",this.Nn,this);var b=Math.round(a.volume);a=!!a.muted;var c=d8(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.L.start();this.o.subscribe("remotePlayerChange",this.Nn,this)}};
g.h.NT=function(){g.Zb(this.F)||jGa(this,this.F);this.G=!1};
g.h.JE=function(a,b){this.D.stop();2==b&&this.pG()};
g.h.Nn=function(){if(L8(this)){this.B.stop();var a=d8(this.o);switch(a.o){case 1080:case 1081:case 1084:case 1085:this.C.G=1;break;case 1082:case 1083:this.C.G=0;break;default:this.C.G=-1}switch(a.o){case 1081:case 1:K8(this,new g.JP(8));this.oG();break;case 1085:case 3:K8(this,new g.JP(9));break;case 1083:case 0:K8(this,new g.JP(2));this.J.stop();J8(this,this.T.getVideoData().lengthSeconds);break;case 1084:K8(this,new g.JP(4));break;case 2:K8(this,new g.JP(4));J8(this,Z7(a));break;case -1:K8(this,
new g.JP(64));break;case -1E3:K8(this,new g.JP(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=d8(this.o).A;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.F=a,jGa(this,a));a=d8(this.o);-1==a.volume||Math.round(this.T.getVolume())==a.volume&&this.T.isMuted()==a.muted||this.L.isActive()||this.TG()}else iGa(this)};
g.h.GE=function(){this.T.V("mdxpreviousnextchange")};
g.h.Nq=function(){L8(this)||iGa(this)};
g.h.zK=function(){this.o.fA()};
g.h.fE=function(a){a&&(a=g.GE("/watch_queue_ajax",{method:"GET",gd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.B)(this.aW,this)}))&&(this.N=(0,g.B)(a.abort,a))};
g.h.aW=function(a,b){var c=new g.aP(g.X(this.T),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.T.V("mdxautoplayupnext",c)};
g.h.xE=function(a){(0,window.isNaN)(a)||this.T.V("mdxnowautoplaying",a)};
g.h.eE=function(){this.T.V("mdxautoplaycanceled")};
g.h.uQ=function(a,b){-1==d8(this.o).o?N8(this,a):b&&this.o.iH(a)};
g.h.TG=function(){if(L8(this)){var a=d8(this.o);this.A.Ia(this.O);a.muted?this.T.mute():this.T.sg();this.T.setVolume(a.volume);this.O=this.A.R(this.T,"onVolumeChange",this.tE)}};
g.h.oG=function(){this.B.stop();if(!this.o.la()){var a=d8(this.o);a.sb()&&K8(this,new g.JP(8));J8(this,Z7(a));this.B.start()}};
g.h.pG=function(){this.D.stop();this.B.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.D.start()};g.t(O8,g.V);O8.prototype.D=function(a){lGa(this,a.state)};g.t(P8,g.wY);P8.prototype.K=function(){var a=this.T.Fc("remote","receivers");a&&1<a.length&&!this.T.Fc("remote","quickCast")?(this.H=g.jb(a,this.D,this),g.xY(this,(0,g.I)(a,this.D)),a=this.T.Fc("remote","currentReceiver"),this.Gf(this.D(a)),this.enable(!0)):this.enable(!1)};
P8.prototype.D=function(a){return a.key};
P8.prototype.Ff=function(a){return"cast-selector-receiver"==a?"Cast...":this.H[a].name};
P8.prototype.Id=function(a){g.wY.prototype.Id.call(this,a);this.T.Xd("remote","currentReceiver",this.H[a]);this.C.Rb()};g.t(Q8,g.zU);g.h=Q8.prototype;g.h.create=function(){cGa(g.cN(g.X(this.player)));this.D.push(g.iG("yt-remote-before-disconnect",this.mS,this));this.D.push(g.iG("yt-remote-connection-change",this.eV,this));this.D.push(g.iG("yt-remote-receiver-availability-change",this.HE,this));this.D.push(g.iG("yt-remote-auto-connect",this.cV,this));this.D.push(g.iG("yt-remote-receiver-resumed",this.bV,this));this.HE()};
g.h.load=function(){this.player.Cv();g.zU.prototype.load.call(this);this.C=new I8(this,this.player,this.o);var a=(a=hGa())?a.currentTime:0;var b=G8()?new c8(B8(),void 0):null;0==a&&b&&(a=Z7(d8(b)));0!=a&&(this.J=a||0,this.player.V("progresssync",a,void 0));kGa(this,this.F,this.F);g.L_(this.player.app,6)};
g.h.unload=function(){this.player.V("mdxautoplaycanceled");this.B=this.A;g.nf(this.C,this.o);this.o=this.C=null;g.zU.prototype.unload.call(this);g.L_(this.player.app,5)};
g.h.Y=function(){g.jG(this.D);g.zU.prototype.Y.call(this)};
g.h.Bn=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.cD.apply(this.C,[a].concat(g.fa(c)))};
g.h.pL=function(){return this.loaded?this.C.suggestion:null};
g.h.kg=function(){return this.o?d8(this.o).kg:!1};
g.h.hasNext=function(){return this.o?d8(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.iQ=function(){var a=d8(this.o),b=this.player.getVideoData();return{allowSeeking:g.X(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Zc():!a.isAdPlaying()&&this.player.Zc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+X7(a):a.C,isPeggedToLive:1>=(a.F?a.B+X7(a):a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+X7(a):a.B,seekableStart:0<a.D?a.D+X7(a):a.D}};
g.h.jQ=function(){this.o&&this.o.gH()};
g.h.kQ=function(){this.o&&this.o.hH()};
g.h.mS=function(a){1==a&&(this.K=this.o?d8(this.o):null)};
g.h.eV=function(){var a=G8()?new c8(B8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.K=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.mf(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.player.getVideoData().videoId&&this.player.HC(a.videoId,Z7(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.HE=function(){this.H=[this.A].concat(eGa());var a=C8()||this.A;R8(this,a);this.player.za("onMdxReceiversChange")};
g.h.cV=function(){var a=C8();R8(this,a)};
g.h.bV=function(){this.B=C8()};
g.h.hQ=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?T7():R8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&T7(),!0):!1}};
g.h.lQ=function(){h8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Hc=function(){return!1};g.xX.remote=Q8;})(_yt_player);
